### PR TITLE
Fix #4, failure on clean compile

### LINKED ISSUE #4: Cannot create war if target directory does not exist
Hi Luke,

Adding `ldap-server:0.1.8` as a dependency to a `Grails 2.3.4` app produces the following error when running `grails war` **when `target` directory does not exist**:

```
Error Fatal error during compilation java.lang.NoClassDefFoundError: org/apache/directory/shared/ldap/exception/LdapNameNotFoundException
```

Any idea what the issue might be? It is causing a bit of an issue when building in a clean environment (fresh checkout from version control, no `target` directory) on a CI server.

### PR DESCRIPTION
**Pull request by double16**
This addresses a failure during a clean compile and building a war.

### CODE REVIEW

**Comment by zoran119** [comment]
I just added the `org.apache.directory.shared:shared-ldap:0.9.12` as a `compile` dependency to my project (thinking it will fix my problem until this is merged), but now I'm getting the following error:

```
Fatal error during compilation java.lang.NoClassDefFoundError: Lorg/apache/directory/server/core/DefaultDirectoryService;
```

@double16, have you seen anything similar?

**Comment by double16** [comment]
I spent at least half a day on this. I do remember an error like this but I
did not try adding a dependency vs plugin.

On Friday, October 3, 2014, Zoran Stojakovic notifications@github.com
wrote:

> I just added the org.apache.directory.shared:shared-ldap:0.9.12 as a
> compile dependency to my project (thinking it will fix my problem until
> this is merged), but now I'm getting the following error:
> 
> Fatal error during compilation java.lang.NoClassDefFoundError: Lorg/apache/directory/server/core/DefaultDirectoryService;
> 
> @double16 https://github.com/double16, have you seen anything similar?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/alkemist/grails-ldap-server/pull/6#issuecomment-57758627
> .

## 

Pat Double
"Ye must be born again." - John 3:7

**Comment by zoran119** [comment]
@alkemist, any chance we can have this looked at/merged in?

**Comment by ldaley** [comment]
Hi @double16 @zoran119 

Sorry, I'm not maintaining this anymore. I'm happy to transfer the code to anyone who would like to take it over.

**Comment by zoran119** [comment]
@alkemist, I'm happy to (try) to look after this.

**Comment by zoran119** [comment]
@alkemist or should I just fork it?

**Pull request merged**
